Movies/Chaos.Movies.WebCore/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Chaos.Movies.WebCore.Controllers
{
    using System.Diagnostics.CodeAnalysis;

    using Chaos.Movies.Contract;
    using Chaos.Movies.Model;
    using Chaos.Movies.Model.Exceptions;

    using Microsoft.AspNetCore.Http;

    public class SearchController : Controller
    {
        public async Task<IActionResult> Search(string searchText)
        {
            var session = await this.ValidateSessionAsync();
            if (session == null)
            {
                return this.RedirectToAction("Index", "Login");
            }

            var result = new List<MovieDto>();
            if (!string.IsNullOrWhiteSpace(searchText))
            {
                var userLanguage = "sv-SE";
                var movies = await Movie.Static.SearchAsync(
                    new SearchParametersDto { RequireExactMatch = false, SearchLimit = 10, SearchText = searchText },
                    session);
                result.AddRange(movies.Select(m => m.ToContract(userLanguage)));
                await Movie.Static.GetUserRatingsAsync(result, session);
                result = result.OrderByDescending(m => m.ExternalRatings.FirstOrDefault()?.Value).ToList();
            }

            return this.View(result.AsReadOnly());
        }

        /// <summary>Validates the current user's session.</summary>
        /// <returns>The <see cref="UserSession"/>.</returns>
        [SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1126:PrefixCallsCorrectly", Justification = "Reviewed. Suppression is OK here.")]
        private async Task<UserSession> ValidateSessionAsync()
        {
            if (!Guid.TryParse(HttpContext.Session.GetString("SessionId"), out var sessionId))
            {
                return null;
            }

            try
            {
                var session = await UserSession.GetSessionAsync(sessionId);
                await session.ValidateSessionAsync();
                return session;
            }
            catch (InvalidSessionException)
            {
                return null;
            }
        }
    }
}

Movies/Chaos.Movies.WebCore/Controllers/ViewController.cs
//-----------------------------------------------------------------------
// <copyright file="ViewController.cs">
//     Copyright (c) Erik Bunnstad. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace Chaos.Movies.WebCore.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Diagnostics.CodeAnalysis;
    using System.Linq;
    using System.Threading.Tasks;

    using Chaos.Movies.Contract;
    using Chaos.Movies.Model;
    using Chaos.Movies.Model.Exceptions;

    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;

    public class ViewController : Controller
    {
        #region Viwes

        public async Task<IActionResult> Movie(int movieId)
        {
            var session = await this.ValidateSessionAsync();
            if (session == null)
            {
                return this.RedirectToAction("Index", "Login");
            }

            var userLanguage = "sv-SE";
            var movie = (await Model.Movie.Static.GetAsync(session, movieId)).ToContract(userLanguage);
            await Model.Movie.Static.GetUserItemDetailsAsync(movie, session, userLanguage);
            var s = new Tuple<MovieDto, ReadOnlyCollection<WatchTypeDto>>(
                movie,
                new ReadOnlyCollection<WatchTypeDto>((await GlobalCache.GetAllWatchTypesAsync()).Select(w => w.ToContract(userLanguage)).ToList()));
            return this.View(s);
        }

        public async Task<IActionResult> Character(int characterId)
        {
            var session = await this.ValidateSessionAsync();
            if (session == null)
            {
                return this.RedirectToAction("Index", "Login");
            }

            var userLanguage = "sv-SE";
            var character = (await Model.Character.Static.GetAsync(session, characterId)).ToContract(userLanguage);
            await Model.Character.Static.GetUserItemDetailsAsync(character, session, userLanguage);
            return this.View(character);
        }

        public async Task<IActionResult> Person(int personId)
        {
            var session = await this.ValidateSessionAsync();
            if (session == null)
            {
                return this.RedirectToAction("Index", "Login");
            }

            var userLanguage = "sv-SE";
            var person = (await Model.Person.Static.GetAsync(session, personId)).ToContract(userLanguage);
            await Model.Person.Static.GetUserItemDetailsAsync(person, session, userLanguage);
            return this.View(person);
        }

        #endregion

        #region Edit

        [HttpPost]
        public async Task<ActionResult> SaveMovieRating(int movieId, int ratingTypeId, int ratingValue)
        {
            var session = await this.ValidateSessionAsync();
            if (session == null)
            {
                return this.RedirectToAction("Index", "Login");
            }

            await Model.Movie.SaveUserRatingAsync(movieId, ratingTypeId, ratingValue, session);
            return Json("true");
        }

        [HttpPost]
        public async Task<ActionResult> SavePersonRating(int movieId, int personId, int roleId, int departmentId, int ratingValue)
        {
            var session = await this.ValidateSessionAsync();
            if (session == null)
            {
                return this.RedirectToAction("Index", "Login");
            }

            await Model.Person.SaveUserRatingAsync(personId, roleId, departmentId, movieId, ratingValue, session);
            return Json("true");
            //return this.RedirectToAction("Movie", new { movieId });
        }

        [HttpPost]
        public async Task<ActionResult> SaveCharacterRating(int movieId, int characterId, int personId, int ratingValue)
        {
            try
            {
                var session = await this.ValidateSessionAsync();
                if (session == null)
                {
                    return this.RedirectToAction("Index", "Login");
                }

                await Model.Character.SaveUserRatingAsync(characterId, personId, movieId, ratingValue, session);
                return Json("true");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        [HttpPost]
        public async Task<ActionResult> SaveWatchMovie(int movieId, DateTime watchDate, bool dateUncertain, int watchTypeId)
        {
            var session = await this.ValidateSessionAsync();
            if (session == null)
            {
                return this.RedirectToAction("Index", "Login");
            }

            await Model.Movie.SaveWatchMovieAsync(movieId, watchDate, dateUncertain, watchTypeId, session);
            return Json("true");
        }

        [HttpPost]
        public async Task<ActionResult> DeleteWatchMovie(int movieId, int watchId, int watchTypeId)
        {
            var session = await this.ValidateSessionAsync();
            if (session == null)
            {
                return this.RedirectToAction("Index", "Login");
            }

            await Model.Movie.DeleteWatchMovieAsync(watchId, movieId, watchTypeId, session);
            return Json("true");
        }

        #endregion

        /// <summary>Validates the current user's session.</summary>
        /// <returns>The <see cref="UserSession"/>.</returns>
        [SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1126:PrefixCallsCorrectly", Justification = "Reviewed. Suppression is OK here.")]
        private async Task<UserSession> ValidateSessionAsync()
        {
            if (!Guid.TryParse(HttpContext.Session.GetString("SessionId"), out var sessionId))
            {
                return null;
            }

            try
            {
                var session = await UserSession.GetSessionAsync(sessionId);
                await session.ValidateSessionAsync();
                return session;
            }
            catch (InvalidSessionException)
            {
                return null;
            }
        }
    }
}

Movies/Chaos.Movies.WebCore/Views/Shared/Cast.cshtml
@using Chaos.Movies.Contract
@model MovieDto
@foreach (var personAsCharacter in Model.Characters)
{
    <div class="row">
        <div class="item">
            <div class="itemContent">
                <a href="@Url.Action("Person", "View", new { personId = personAsCharacter.PersonInRole.Person.Id})">
                    <div class="name">
                        <h4>@personAsCharacter.PersonInRole.Person.Name</h4>
                    </div>
                </a>
                <div class="ratingRow">
                    <div class="ratingIcon">
                        <span class="ratingScore">@personAsCharacter.PersonInRole.UserRating.DisplayValue</span>
                        <img src="~/images/User.svg" />
                    </div>
                    <div class="ratingBackground">
                        <div style="background-color: @personAsCharacter.PersonInRole.UserRating.HexColor; height: 100%; width: @personAsCharacter.PersonInRole.UserRating.Width;"></div>
                    </div>
                    <div class="ratingStars clickable" onclick="savePersonRating(event, this, false, @personAsCharacter.PersonInRole.Person.Id, @personAsCharacter.PersonInRole.Role.Id, @personAsCharacter.PersonInRole.Department.Id);">
                        <img src="~/images/StarRowTransparent.svg" />
                    </div>
                </div>
                <div class="ratingRow">
                    <div class="ratingIcon">
                        <span class="ratingScore">@personAsCharacter.PersonInRole.Person.UserRating.DisplayValue</span>
                        <img src="~/images/User.svg" />
                    </div>
                    <div class="ratingBackground">
                        <div style="background-color: @personAsCharacter.PersonInRole.Person.UserRating.HexColor; height: 100%; width: @personAsCharacter.PersonInRole.Person.UserRating.Width;">
                        </div>
                    </div>
                    <div class="ratingStars">
                        <img src="~/images/StarRowTransparent.svg" />
                    </div>
                </div>
                <div class="ratingRow">
                    <div class="ratingIcon">
                        <span class="ratingScore">@personAsCharacter.PersonInRole.TotalRating.DisplayValue</span>
                        <img src="~/images/CMDB.png" />
                    </div>
                    <div class="ratingBackground">
                        <div style="background-color: @personAsCharacter.PersonInRole.TotalRating.HexColor; height: 100%; width: @personAsCharacter.PersonInRole.TotalRating.Width;">
                        </div>
                    </div>
                    <div class="ratingStars">
                        <img src="~/images/StarRowTransparent.svg" />
                    </div>
                </div>
                <div class="ratingRow">
                    <div class="ratingIcon">
                        <span class="ratingScore">@personAsCharacter.PersonInRole.Person.TotalRating.DisplayValue</span>
                        <img src="~/images/CMDB.png" />
                    </div>
                    <div class="ratingBackground">
                        <div style="background-color: @personAsCharacter.PersonInRole.Person.TotalRating.HexColor; height: 100%; width: @personAsCharacter.PersonInRole.Person.TotalRating.Width;">
                        </div>
                    </div>
                    <div class="ratingStars">
                        <img src="~/images/StarRowTransparent.svg" />
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Person", "View", new { personId = personAsCharacter.PersonInRole.Person.Id})">
                <div class="listIcon">
                    <img src="~/images/icons/Male.png" />
                </div>
            </a>
        </div>
        <div class="item">
            <a href="@Url.Action("Character", "View", new { characterId = personAsCharacter.Character.Id})">
                <div class="listIcon">
                    <img src="~/images/icons/Female.png" />
                </div>
            </a>
            <div class="itemContent">
                <a href="@Url.Action("Character", "View", new { characterId = personAsCharacter.Character.Id})">
                    <div class="name">
                        <h4>@personAsCharacter.Character.Name</h4>
                    </div>
                </a>
                <div class="ratingRow">
                    <div class="ratingIcon">
                        <span class="ratingScore">@personAsCharacter.UserRating.DisplayValue</span>
                        <img src="~/images/User.svg" />
                    </div>
                    <div class="ratingBackground">
                        <div style="background-color: @personAsCharacter.UserRating.HexColor; height: 100%; width: @personAsCharacter.UserRating.Width;"></div>
                    </div>
                    <div class="ratingStars clickable" onclick="saveCharacterRating(event, this, false, @personAsCharacter.Character.Id, @personAsCharacter.PersonInRole.Person.Id);">
                        <img src="~/images/StarRowTransparent.svg" />
                    </div>
                </div>
                <div class="ratingRow">
                    <div class="ratingIcon">
                        <span class="ratingScore">@personAsCharacter.Character.UserRating.DisplayValue</span>
                        <img src="~/images/User.svg" />
                    </div>
                    <div class="ratingBackground">
                        <div style="background-color: @personAsCharacter.Character.UserRating.HexColor; height: 100%; width: @personAsCharacter.Character.UserRating.Width;">
                        </div>
                    </div>
                    <div class="ratingStars">
                        <img src="~/images/StarRowTransparent.svg" />
                    </div>
                </div>
                <div class="ratingRow">
                    <div class="ratingIcon">
                        <span class="ratingScore">@personAsCharacter.TotalRating.DisplayValue</span>
                        <img src="~/images/CMDB.png" />
                    </div>
                    <div class="ratingBackground">
                        <div style="background-color: @personAsCharacter.TotalRating.HexColor; height: 100%; width: @personAsCharacter.TotalRating.Width;">
                        </div>
                    </div>
                    <div class="ratingStars">
                        <img src="~/images/StarRowTransparent.svg" />
                    </div>
                </div>
                <div class="ratingRow">
                    <div class="ratingIcon">
                        <span class="ratingScore">@personAsCharacter.Character.TotalRating.DisplayValue</span>
                        <img src="~/images/CMDB.png" />
                    </div>
                    <div class="ratingBackground">
                        <div style="background-color: @personAsCharacter.Character.TotalRating.HexColor; height: 100%; width: @personAsCharacter.Character.TotalRating.Width;">
                        </div>
                    </div>
                    <div class="ratingStars">
                        <img src="~/images/StarRowTransparent.svg" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    savePersonRating = function (event, sender, rightToLeft, personId, roleId, departmentId) {
        var ratingValue = GetRatingFromPosition(event, sender, rightToLeft, 200);
        $.ajax({
            url: "@Url.Action("SavePersonRating", "View")",
            data: { movieId: @Model.Id, personId: personId, roleId: roleId, departmentId: departmentId, ratingValue: ratingValue },
            type: "POST",
            success: function () {
                $(sender).prev().children().first().css("width", ratingValue * 10 + "%");
                $(sender).prev().prev().children().first().text(ratingValue);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                showError(xhr.responseText);
            }
        });
    };
    
    saveCharacterRating = function (event, sender, rightToLeft, characterId, personId) {
        var ratingValue = GetRatingFromPosition(event, sender, rightToLeft, 200);
        $.ajax({
            url: "@Url.Action("SaveCharacterRating", "View")",
            data: { movieId: @Model.Id, characterId: characterId, personId: personId, ratingValue: ratingValue },
            type: "POST",
            success: function () {
                $(sender).prev().children().first().css("width", ratingValue * 10 + "%");
                $(sender).prev().prev().children().first().text(ratingValue);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                showError(xhr.responseText);
            }
        });
    };
</script>

Movies/Chaos.Movies.WebCore/Views/Shared/Crew.cshtml
@using Chaos.Movies.Contract
@model MovieDto
<!--Dont show actors-->
@foreach (var department in Model.People.GroupBy(p => p.Department.Id).Select(d => d.First().Department))
{
    <h3 class="accordion-toggle" data-toggle="collapse" data-target="#Department_@department.Id">@department.Titles.First().Title</h3>
    <div id="Department_@department.Id" class="collapse in">
        @foreach (var personInRole in Model.People.Where(p => p.Department.Id == department.Id))
        {
            <div class="row">
                <div class="item">
                    <a href="@Url.Action("Person", "View", new { personId = personInRole.Person.Id})">
                        <div class="listIcon medium">
                            <img src="~/images/icons/Male.png" />
                        </div>
                    </a>
                    <div class="itemContent">
                        <a href="@Url.Action("Person", "View", new { personId = personInRole.Person.Id})">
                            <div class="name">
                                <h4>@personInRole.Person.Name - @personInRole.Role.Titles.First(t => t.LanguageType == LanguageType.Default).Title</h4>
                            </div>
                        </a>
                        <div class="ratingRow">
                            <div class="ratingIcon">
                                <span class="ratingScore">@personInRole.UserRating.DisplayValue</span>
                                <img src="~/images/User.svg" />
                            </div>
                            <div class="ratingBackground">
                                <div style="background-color: @personInRole.UserRating.HexColor; height: 100%; width: @personInRole.UserRating.Width;"></div>
                            </div>
                            <div class="ratingStars clickable" onclick="savePersonRating(event, this, false, @personInRole.Person.Id, @personInRole.Role.Id, @personInRole.Department.Id);">
                                <img src="~/images/StarRowTransparent.svg" />
                            </div>
                        </div>
                        <div class="ratingRow">
                            <div class="ratingIcon">
                                <span class="ratingScore">@personInRole.Person.UserRating.DisplayValue</span>
                                <img src="~/images/User.svg" />
                            </div>
                            <div class="ratingBackground">
                                <div style="background-color: @personInRole.Person.UserRating.HexColor; height: 100%; width: @personInRole.Person.UserRating.Width;">
                                </div>
                            </div>
                            <div class="ratingStars">
                                <img src="~/images/StarRowTransparent.svg" />
                            </div>
                        </div>
                        <div class="ratingRow">
                            <div class="ratingIcon">
                                <span class="ratingScore">@personInRole.TotalRating.DisplayValue</span>
                                <img src="~/images/CMDB.png" />
                            </div>
                            <div class="ratingBackground">
                                <div style="background-color: @personInRole.TotalRating.HexColor; height: 100%; width: @personInRole.TotalRating.Width;">
                                </div>
                            </div>
                            <div class="ratingStars">
                                <img src="~/images/StarRowTransparent.svg" />
                            </div>
                        </div>
                        <div class="ratingRow">
                            <div class="ratingIcon">
                                <span class="ratingScore">@personInRole.Person.TotalRating.DisplayValue</span>
                                <img src="~/images/CMDB.png" />
                            </div>
                            <div class="ratingBackground">
                                <div style="background-color: @personInRole.Person.TotalRating.HexColor; height: 100%; width: @personInRole.Person.TotalRating.Width;">
                                </div>
                            </div>
                            <div class="ratingStars">
                                <img src="~/images/StarRowTransparent.svg" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}

Movies/Chaos.Movies.WebCore/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chaos Movies</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Chaos Movies</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Search" asp-action="Search">Search</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Chaos Movies - Erik Bunnstad</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <div id="errorContainer" class="errorContainer" onclick="hideError();">
        <div id="errorMessage" class="errorMessage">

        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>